version: "3"
services:
  strapi:
    image: naskio/strapi
    environment:
      NODE_ENV: development # Ou use "production" se estiver em produção
    ports:
      - "1337:1337"
    volumes:
      - ./app:/srv/app
